switch to systemd unit, set alsa volume to maximum

diff --git a/steelseries-arctis-pro-wireless b/steelseries-arctis-pro-wireless
--- a/steelseries-arctis-pro-wireless
+++ b/steelseries-arctis-pro-wireless
@@ -17,27 +17,53 @@ elif [ "$UID" == "0" ]; then
     # Check process table for users running PulseAudio
     for user in `ps axc -o user,command | grep pulseaudio | cut -f1 -d' ' | sort | uniq`;
     do
-	# And relaunch ourselves for each of those users.
-	su $user -c "bash $0"
+	    # And relaunch ourselves for each of those users.
+	    su $user -c "bash $0" &
     done
 else
-    # Set PULSE_RUNTIME_DIR for pacmd
-    export PULSE_RUNTIME_PATH=/run/user/$(id -u $user)/pulse/
-
-    # Device needs to be manually loaded
-    pacmd load-module module-alsa-sink device=hw:CARD=Wireless,DEV=1
-
     # Running as non-root, so adjust our PulseAudio directly.
     pacmd set-default-sink $OUTPUT >/dev/null 2>&1
     pacmd set-default-source $INPUT >/dev/null 2>&1
 
     for playing in $(pacmd list-sink-inputs | awk '$1 == "index:" {print $2}')
     do
-	pacmd move-sink-input $playing $OUTPUT >/dev/null 2>&1
+	    pacmd move-sink-input $playing $OUTPUT >/dev/null 2>&1
     done
 
     for recording in $(pacmd list-source-outputs | awk '$1 == "index:" {print $2}')
     do
-	pacmd move-source-output $recording $INPUT >/dev/null 2>&1
+	    pacmd move-source-output $recording $INPUT >/dev/null 2>&1
+    done
+
+    # Escaped pattern of card to look for in aplay's output
+    CARD_PATTERN="Wireless \[Arctis Pro Wireless\]"
+    # Control patterns to look for in amixer's output for mono and stereo (chat and game)
+    CONTROL_PATTERNS=("name='PCM Playback Volume'" "name='PCM Playback Volume',index=1")
+
+    # Extract card number form output
+    CARD_NUM=$(aplay -l | grep -oP "(?<=card )\d+(?=:.*$CARD_PATTERN)" | head -n 1)
+    if [ -z "$CARD_NUM" ]; then
+        echo "Sound card not found"
+        exit 1
+    fi
+    echo "Found device with sound card number $CARD_NUM"
+
+    for CONTROL_PATTERN in "${CONTROL_PATTERNS[@]}"
+    do
+        echo $CONTROL_PATTERN
+    done
+
+    for CONTROL_PATTERN in "${CONTROL_PATTERNS[@]}"
+    do
+        # Extract control number from output
+        CONTROL_NUM=$(amixer -c "$CARD_NUM" controls | grep -oP "(?<=^numid=)\d+(?=.*$CONTROL_PATTERN$)")
+        if [ -z "$CONTROL_NUM" ]; then
+            echo "Control $CONTROL_PATTERN not found for card"
+            exit 1
+        fi
+        echo "Found control with numid=$CONTROL_NUM"
+
+        amixer -c "$CARD_NUM" cset "numid=$CONTROL_NUM" 100%
+        echo "Volume set to 100% for $CONTROL_PATTERN"
     done
 fi
